[package]
name = "better_btree"
version = "0.1.3"
authors = ["Ben-Lichtman <>"]
edition = "2018"
description = "A reimplementation of a btree"
repository = "https://github.com/Ben-Lichtman/better_btree"
license = "MIT OR Apache-2.0"

[dependencies]
